spring:
  profiles.active: dev
---

spring:
  profiles: dev
spring.datasource:
  url: jdbc:mysql://localhost:3306/health?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver
  validationQuery: SELECT 1 FROM DUAL
  max-wait: 10000
  max-active: 100
  test-on-borrow: true
spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update
spring.redis:
  host: 127.0.0.1
  password:
  port: 6379
logging:
  file: F:/log/health/business/debug
upload:
  physicalPath: F:/upload/health/
  webPath: upload/
server:
  context-path: /api
springfox.documentation.swagger.v2.path: /api-docs
---

spring:
  profiles: test
spring.datasource:
  url: jdbc:mysql://localhost:3306/health?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver
  validationQuery: SELECT 1 FROM DUAL
  max-wait: 10000
  max-active: 100
  test-on-borrow: true
spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update
logging:
  file: F:/log/loan-api/business/debug
---

spring:
  profiles: prod
spring.datasource:
  url: jdbc:mysql://localhost:3308/health?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver
  validationQuery: SELECT 1 FROM DUAL
  max-wait: 10000
  max-active: 100
  test-on-borrow: true
spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update
upload:
  physicalPath: C:/upload/loan/
  webPath: upload/    
    