spring:
  profiles.active: dev
---

#开发环境配置
spring:
  profiles: dev
spring.datasource:
  url: jdbc:mysql://localhost:3306/health?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  username: root
  password: 
  driver-class-name: com.mysql.jdbc.Driver
  validationQuery: SELECT 1 FROM DUAL
  max-wait: 10000
  max-active: 100
  test-on-borrow: true
spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update
spring.redis:
  host: 127.0.0.1
  password:
  port: 6379
logging:
  file: F:/log/health/client-api
upload:
  physicalPath: F:/upload/loan/
  webPath: upload/
server:
  context-path: /api
springfox.documentation.swagger.v2.path: /api-docs
#跨域请求设置
cors:
  allowed-origin: http://localhost:9001
---

#测试环境配置
spring:
  profiles: test

---

#生产环境配置
spring:
  profiles: prod
spring.datasource:
  url: jdbc:mysql://localhost:3306/health?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  username: root
  password: wabu2016
  driver-class-name: com.mysql.jdbc.Driver
  validationQuery: SELECT 1 FROM DUAL
  max-wait: 10000
  max-active: 100
  test-on-borrow: true
spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update
spring.redis:
  host: 127.0.0.1
  password:
  port: 6379
upload:
  physicalPath: /home/tomcat/upload/health/
  webPath: upload/
server:
  context-path: /v1
springfox.documentation.swagger.v2.path: /api-docs
#跨域请求设置
cors:
  #暂未确认站点，允许所有请求
  allowed-origin: '*'
    